[tool.poetry]
name = "terrarium"
version = "0.1.1"
description = "Computer-aided process planner for scientific processes."
authors = ["jvrana <justin.vrana@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
dill = "^0.2.9"
pandas = "^0.24.2"
webcolors = "^1.9"
colorama = "^0.4.1"
arrow = "^0.14.2"
black = {version = "^18.3-alpha.0",allows-prereleases = true}

[tool.poetry.dev-dependencies]
pytest = "^4.6"
vcrpy = "^2.0"
pre-commit = "^1.17"
pytest-benchmark = "^3.2"
pygal = "^2.4"
pygaljs = "^1.0"
keats = "^0.2.24"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
