[tool.poetry]
name = "terrarium"
version = "0.1.0"
description = ""
authors = ["Justin Vrana <justin.vrana@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
dill = "^0.2.9"
webcolors = "^1.9"
colorama = "^0.4.1"
termcolor = "^1.1"
pydent = "=0.1.2a"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0",allows-prereleases = true}
pytest = "^4.6"
pre-commit = "^1.17"
vcrpy = "^2.0"
pytest-cov = "^2.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
