[tool.poetry]
name = "terrarium"
version = "0.1.0"
description = ""
authors = ["jvrana <justin.vrana@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
dill = "^0.2.9"
pandas = "^0.24.2"
webcolors = "^1.9"
colorama = "^0.4.1"
arrow = "^0.14.2"
pydent = {path = "../trident"}
black = {version = "^18.3-alpha.0",allows-prereleases = true}

[tool.poetry.dev-dependencies]
pytest = "^4.6"
vcrpy = "^2.0"
pre-commit = "^1.17"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
